# -*- coding: utf-8 -*-
"""paswsword generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UvRcLEinKtvtr_7WhynOQ62-AfZUV99G
"""

import random
import string

def generate_password(length, use_letters, use_numbers, use_symbols):
    characters = ""
    if use_letters:
        characters += string.ascii_letters
    if use_numbers:
        characters += string.digits
    if use_symbols:
        characters += string.punctuation

    if not characters:
        print("Please select at least one character type.")
        return None

    password = ''.join(random.choice(characters) for _ in range(length))
    return password

def main():
    print("Random Password Generator")
    try:
        length = int(input("Enter password length: "))
        use_letters = input("Include letters? (yes/no): ").strip().lower() == "yes"
        use_numbers = input("Include numbers? (yes/no): ").strip().lower() == "yes"
        use_symbols = input("Include symbols? (yes/no): ").strip().lower() == "yes"

        password = generate_password(length, use_letters, use_numbers, use_symbols)
        if password:
            print(f"Generated password: {password}")
    except ValueError:
        print("Please enter a valid number for password length.")

if __name__ == "__main__":
    main()